on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: aarch64-unknown-linux-musl
                  override: true
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: x86_64-unknown-linux-musl
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --target aarch64-unknown-linux-musl
            - uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --target x86_64-unknown-linux-musl