[package]
name = "easypwned"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bloomfilter = "1.*"
anyhow = "*"
axum = "0.6.*"
tokio = { version = "1.*", features = ["full"]}
serde = "1.0.*"
serde_json = "1.0.*"
serde_derive = "1.0.*"
tracing = "0.1.*"
tracing-subscriber = "0.3.*"
bincode = { version = "1.3.3"}
sha-1 = "0.*"
base16ct = { version = "0.1", features = ["alloc", "std"]}
structopt = "0.*"
byteorder = "1.*"