[application]
name = "Easypwdned"
default_platform = "web"
out_dir = "../dist"
asset_dir = "../public"

[web.app]
title = "easypwned | easybill.de"

[web.watcher]
reload_html = true
watch_path = ["src", "../public"]

[web.resource]
style = ["tailwind.css"]
script = []

[web.resource.dev]
style = []
script = []