on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'

name: compile

jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/resuseable/rust_prepare.yml
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          cp target/x86_64-unknown-linux-musl/release/easypwned easypwned
          docker buildx build --platform linux/amd64 -t easybill/easypwned:latest_amd64 --push .
          cp target/aarch64-unknown-linux-musl/release/easypwned easypwned
          docker buildx build --platform linux/arm64 -t easybill/easypwned:latest_arm64 --push .
          docker manifest create easybill/easypwned:latest easybill/easypwned:latest_amd64 easybill/easypwned:latest_arm64
          docker manifest push easybill/easypwned:latest
      -
        name: Build and push release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker manifest create easybill/easypwned:${{ steps.vars.outputs.tag }} easybill/easypwned:latest_amd64 easybill/easypwned:latest_arm64
          docker manifest push easybill/easypwned:${{ steps.vars.outputs.tag }}
      - name: Release Build
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp target/aarch64-unknown-linux-musl/release/easypwned easypwned_${{ steps.vars.outputs.tag }}_linux_aarch64
          cp target/x86_64-unknown-linux-musl/release/easypwned easypwned_${{ steps.vars.outputs.tag }}_linux_x86_64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            easypwned_${{ steps.vars.outputs.tag }}_linux_aarch64
            easypwned_${{ steps.vars.outputs.tag }}_linux_x86_64